Document: maru-mflinger-client
Title: Debian maru-mflinger-client Manual
Author: <insert document author here>
Abstract: This manual describes what maru-mflinger-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/maru-mflinger-client/maru-mflinger-client.sgml.gz

Format: postscript
Files: /usr/share/doc/maru-mflinger-client/maru-mflinger-client.ps.gz

Format: text
Files: /usr/share/doc/maru-mflinger-client/maru-mflinger-client.text.gz

Format: HTML
Index: /usr/share/doc/maru-mflinger-client/html/index.html
Files: /usr/share/doc/maru-mflinger-client/html/*.html
